### ISSUE TITLE
Incorrect handling of unicode file names

### ISSUE THREAD

**Issue by dp1** [edomora97/task-maker-rust#105]
When run in a narrow enough terminal tmr can try to split file names in the middle of a multibyte character, crashing.

Running on a terminal with `101` columns, it fails when building a solution called `N²_smart.cpp` by trying to split inside the `²`:

![Screenshot from 2022-12-24 11-43-50](https://user-images.githubusercontent.com/3639429/209432804-4870d3cf-de52-4b47-bf34-6d848d408221.png)

**Comment by edomora97** [comment]
https://github.com/edomora97/task-maker-rust/blob/9c5b4a48d3d63af23a93b652f3ef020c991dd5d3/task-maker-format/src/ui/curses.rs#L409-L414

Probably related
