### ISSUE TITLE
fuzz-checker is hard to use

### ISSUE THREAD

**Issue by Virv12** [edomora97/task-maker-rust#117]
Problems I found while trying to use `task-maker-tools fuzz-checker`:
- [x] It defaults to `c++14` against everything else defaulting to `c++17`, also it ignores `TM_CXX_STD_VERSION`.
- [x] `EXIT` is not marked `[[noreturn]]`.
- [x] It gives warnings on constant global variables and static functions (he thinks they are static variables).
- [x] `const` cannot appear in `main`'s signature.

**Comment by edomora97** [comment]
Everything listed should be fixed!
