### ISSUE TITLE
Fuzzer requests

### ISSUE THREAD

**Issue by veluca93** [edomora97/task-maker-rust#47]
- Set unlimited stack for the checker
- Provide the fuzzer input in the fail/ folder

**Comment by veluca93** [comment]
Maybe set the checker timelimit from the task timelimit?

**Comment by edomora97** [comment]
The checker time limit in cms is 10s regardless of the task time limit:

https://github.com/cms-dev/cms/blob/0401c5336b34b1731736045da4877fef11889274/cms/grading/steps/trusted.py#L146

and it can be changed in the configuration file.

----

In task-maker-rust the checker (as of now) has no time or memory limit. To be honest this can be considered a bug if tmr will be used for as a backend evaluation system.

https://github.com/edomora97/task-maker-rust/blob/94adddbe7f202d0ca22dcb36fa05ffed397f7c01/task-maker-format/src/ioi/dag/checker.rs#L94
