### ISSUE TITLE
PPA

### ISSUE THREAD

**Issue by dp1** [edomora97/task-maker-rust#48]
It would be nice to have task-maker-rust as a package in a ppa

**Comment by edomora97** [comment]
I like the idea, however after some investigation it doesn't seem to be easy to publish Rust packages to launchpad.

From what I managed to understand, the package policy requires you to publish the sources of the package, as well as the ones of all the dependencies (https://wiki.debian.org/Teams/RustPackaging/Policy). It should be possible using `cargo-vendor`, but I've zero experience with the Debian tools and I wasn't able to find good guides on how to do it. If you or someone else is willing to try I can try to help and integrate the deployment to the CI pipeline.

**Comment by dp1** [comment]
I've been working on a solution [here](https://github.com/dp1/task-maker-rust-ppa), it's now building the latest release at [ppa:dariop1/task-maker-rust](https://launchpad.net/~dariop1/+archive/ubuntu/task-maker-rust) for all supported Ubuntu versions (currently `bionic focal impish jammy kinetic`).

The 18.04 builds are failing due to a missing dependency (probably just a version that's too recent), so I'll try to fix that when I have time, but everything else seems to be working properly.

**Comment by edomora97** [comment]
What an amazing job! I've added the instructions in the README.
