### ISSUE TITLE
Clear and/or overwrite solution checks

### ISSUE THREAD

**Issue by cip999** [edomora97/task-maker-rust#57]
Can come in handy when subtasks are restructured and former solution checks become obsolete. As of now, one has to manually remove the preexisting checks from all solution files. It would be nice to have a `task-maker-tools` subcommand for this.

**Comment by dp1** [comment]
+1 on this one, something like `task-maker-tools update-solution-checks` (or `add-solution-checks` with a flag to overwrite) could come in handy.

**Comment by edomora97** [comment]
I've implemented `--overwrite` (or `-o` for short) in `task-maker-tools add-solution-checks`. It removes the existing checks before adding the new ones.
